### ISSUE TITLE
Allow local testing without Cognito

### ISSUE THREAD

**Issue by danielrbradley** [o2Labs/office-booker#11]
Avoid having to do an AWS deployment before being able to run the application locally.

## Possible solution

Provide stub authentication method which does an alternative local 'verification' instead of using Cognito and SES. 

- The client could have a configuration option to bypass the Amplify library and allow and email address and code.
- The local server setup could use the same stub auth as the integration tests which just passes the email address instead of the bearer token.

**Comment by AtifKhokhar** [comment]
Another solution could be to use docker: https://github.com/humanmade/local-cognito .

**Comment by danielrbradley** [comment]
@AtifKhokhar yes, worth looking at - we'd need to understand how it works with the custom challenge which we currently implement using Lambda hooks.

**Comment by AtifKhokhar** [comment]
i feel like using this is better @danielrbradley : https://www.npmjs.com/package/cognito-local
its well documented and you can configure it.

**Comment by danielrbradley** [comment]
@AtifKhokhar Same question still applies - does it integrate with custom challenges? If not we'd still need to adjust the core part of our with flow.
