### ISSUE TITLE
Empty error dialog on Help screen after logging out

### ISSUE THREAD

**Issue by chapmanio** [o2Labs/office-booker#115]
![Screenshot 2020-10-20 at 09 42 36](https://user-images.githubusercontent.com/10833481/96562365-99e2eb80-12b8-11eb-9927-6a86824a0625.png)

**Comment by AtifKhokhar** [comment]
just tested on my computer running locally on both chrome and safari and have not encountered this empty error dialog popping up.

**Comment by danielrbradley** [comment]
Yup, just tested this again too and looks like it might have resolved itself.

@chapmanio happy to close or can you still reproduce the issue?

**Comment by chapmanio** [comment]
It's still happening for me https://office.o2lab.co.uk/help shows the error dialog when not logged in.

**Comment by chapmanio** [comment]
If I clear site data in Chrome it seems to stop the message, but after logging in again, if I then log-out and go to the help screen it comes back.

**Comment by aangelisc** [comment]
I concur with @chapmanio, I also see the error following the same steps
