### ISSUE TITLE
Restart login session after timeout or multiple wrong attempts

### ISSUE THREAD

**Issue by danielrbradley** [o2Labs/office-booker#16]
## Problem

If the code is entered incorrectly 3 times a "Bad username or password" message is displayed. Subsequent attempts will be shown "Invalid session for the user".

If the user waits around 5 minutes then the session will expire and any attempt to enter the code will receive the error: "Invalid session for the user".

## Proposed Solution

1. Improve the error message shown to the user - catch the error from Cognito and instead show something like "Login code expired, please try again".
2. Automatically reload the login screen. Currently, even clicking the home icon in the corner won't take you back to re-enter your email address. An even nicer extension of this would be to prompt to re-send the email having confirmed their email address is definitely correct.

**Comment by chapmanio** [comment]
I think item 1 of the proposed solution definitely needs to happen.  I like the idea of also then changing the view to include some extra text as well, e.g.:

> Your login code has now expired, _send a new code to **email**_.

With the latter being a link to trigger the code generation/email send again.  We can stick a small loading spinner with the text and then replace it with:

> A new code has been sent to **email**, please enter it below.

If that all works without the need to refresh the page it would be very slick.  If not, the simpler option is to show that text with the link being `start again` and a link back to the home URL.
