### ISSUE TITLE
Upcoming bookings page should not show previous bookings

### ISSUE THREAD

**Issue by danielrbradley** [o2Labs/office-booker#27]
The API returns _all_ bookings for the user. These are only removed based on the data retention policy.

Perhaps show the previous bookings separately somewhere on the page?

**Comment by AtifKhokhar** [comment]
got this so far :
![image](https://user-images.githubusercontent.com/18725139/88292800-05391380-ccf2-11ea-9ed3-21874e3f86bd.png)
any tips on how it could look better? 
@danielrbradley @Jumee-LDN @chapmanio ??

**Comment by danielrbradley** [comment]
That looks like a good solid design to me - no fuss, no mess.

**Comment by AtifKhokhar** [comment]
initially thought about swapping 'at' with '@' , so it was '21st Jul@The Office' but then decided against it as it can be confusing to some.
