### ISSUE TITLE
Global reducer needs to account for parking selections

### ISSUE THREAD

**Issue by chapmanio** [o2Labs/office-booker#63]
Currently, when you make a booking an event is dispatched to the global reducer, to update the count for the selected office, causing reactive behaviour across the app.  This is **not** happening for parking.

The reducer should be updated to take the parking selection in with the payload, and then update accordingly.

**Comment by chapmanio** [comment]
This has brought up numerous other issues, including:

- Admin behaviour doesn't update global state
  - Therefore any changes aren't then reflected on the main app without a refresh
  - Updating global state doesn't work as expected due to user-specific data retrieved from `getBookings`
- Re-retrieving data from the api on (some) page changes unnecessarily
  - If the data is in global state already we shouldn't re-retrieve it

The final point raises another question, should we actually be re-retrieving data from the data on each page change to make sure we have the most up-to-date data?  I would suggest not to reduce calls to the API, an app refresh would retrieve the latest data.

Is there anything we could do to periodically check for updated data, if they haven't interacted with the app for a while, or when they revisit an existing open page.  @danielrbradley do you have any thoughts?

**Comment by danielrbradley** [comment]
I think I'd prefer up to date information over saving requests if in doubt.

Auto refresh sounds good too.

I wonder if we'd be better splitting the context into smaller parts - separate the admin from the main booking portal.
