### ISSUE TITLE
View booking list should show parking choice

### ISSUE THREAD

**Issue by chapmanio** [o2Labs/office-booker#64]
Same should apply to the previous bookings

**Comment by AtifKhokhar** [comment]
going to use the existing button logic for upcoming bookings: 
![image](https://user-images.githubusercontent.com/18725139/88921560-a9790800-d266-11ea-8f90-00aa0543722c.png)

and previous bookings just have a suffix of with parking at the end

**Comment by AtifKhokhar** [comment]
here is what i have for upcoming bookings section: 
![image](https://user-images.githubusercontent.com/18725139/88922340-e2fe4300-d267-11ea-9dd5-aaa6529b9b4f.png)

**Comment by chapmanio** [comment]
I'm still not sold on the icon with the button, but I can't think of any better way to do it on the home page so it'll do for now.  Makes sense to use it here too for consistency.

**Comment by AtifKhokhar** [comment]
here is how it looks now : 
![image](https://user-images.githubusercontent.com/18725139/88940884-3f6d5c80-d280-11ea-8800-00cd223a10a1.png)
