### ISSUE TITLE
Disable cancelling previous bookings on API

### ISSUE THREAD

**Issue by danielrbradley** [o2Labs/office-booker#66]
If the booking's for a previous day, should we disable removing it?

Might admins want to remove a specific record for some other purpose ... if the user didn't actually visit?

Would we prefer to have the previous bookings as an accurate record and so make them immutable?

**Comment by chapmanio** [comment]
Yes we should not allow bookings in past dates to be cancelled.

**Comment by danielrbradley** [comment]
Still needs to be completed on API
