### ISSUE TITLE
Can't book for next week in Edge

### ISSUE THREAD

**Issue by danielrbradley** [o2Labs/office-booker#78]
Edge does not unhide elements correctly on the page.

Tested using Edge 44.19041.1.0
EdgeHTML 18.19041

Might be related to this issue around hiding & unhiding elements https://stackoverflow.com/questions/48640892/elements-not-being-rendered-in-microsoft-edge

> when I look at the following week nothing is listed so I am unable to book

> in IE the next week appeared with no listing at all 
> the MS IE wont show so it was a browser problem
> copied link into google chrome and it worked there

![image](https://user-images.githubusercontent.com/331676/92461188-df43d180-f1c0-11ea-8dc2-1bd3c691185f.png)

**Comment by danielrbradley** [comment]
> If I use Internet explorer I can only book for the week we are in whereas colleagues using chrome can books weeks in advance.
> How do I fix this so I can book a week or more in advance.

**Comment by chapmanio** [comment]
I am unable to replicate this based on the information provided.  Using Internet Explorer 11 I can log in to the app, change to a week in the future, book and cancel without issues or console errors.

The response time is slow but it always succeeds, but this may be related to the laptop I am using.

My recommendation is to push for more details, including steps to reproduce their issue with a detailed account of exactly happens (compared to what they are expecting, etc).  Ideally we would do a screen-share as they demonstrate the issue.

**Comment by chapmanio** [comment]
I have been able to make a booking without it showing up.  The loading status appeared and then disappeared with no booking showing up.  If I refresh the page the booking is in place and confirmed - but I received no error messages.

I think a clear banner at the top saying the site is optimised for modern browsers with a link to something like https://browsehappy.com/ may be a good idea.  The wording is important to say it will work with IE but is not optimised, or not guaranteed for IE?  Open for suggestions on this...
